### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
https://anaconda.org/conda-forge/django-allauth/files
https://anaconda.org/conda-forge/django-allauth/0.54.0/download/noarch/django-allauth-0.54.0-pyhd8ed1ab_0.conda is available closing

**Comment by jacksund** [comment]
@rxm7706 was there something that you were trying to fix? I've been monitoring the feedstock and merging PR as needed, but didn't know of any issues

**Comment by rxm7706** [comment]
Hi @jacksund , 
I noticed that the last build failed - https://github.com/conda-forge/django-allauth-feedstock/runs/12481167836 and version 0,54 that you merged never got deployed to conda forge. Thats all I wanted to fix. 

I was able to rerun and this time v0.54 deployed without any issues - https://github.com/conda-forge/django-allauth-feedstock/runs/14422187305 - Thank You.

**Comment by jacksund** [comment]
Ah gotcha. Somehow I didn't get pinged for that failure. Thanks for fixing that!

**Pull request closed without merging**
